version: "2"
services:
  mariadb:
    image: mariadb:10
    container_name: my_mariadb
    expose:
      - 3306
    volumes:
      - data:/var/lib/mysql
      - ${VOLUME_PATH}/backup:/backup
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    restart: unless-stopped

  backup:
    build: .
    image: fradelg/mysql-cron-backup
    depends_on:
      - mariadb
    volumes:
      - ${VOLUME_PATH}/backup:/backup
      - ${MYSQL_DATA_PATH}:/mysqldata
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_ROOT_USER}
      - MYSQL_PASS=${MYSQL_ROOT_PASSWORD}
      - MAX_BACKUPS=${MAX_BACKUPS}
      - INIT_BACKUP=${INIT_BACKUP}
      - CRON_TIME=${CRON_TIME}
      - CRON_TIME_RSYNC=${CRON_TIME_RSYNC}
      - BINLOG_DIR=/mysqldata/
      - REMOTE_BACKUP_SSH_IP=${REMOTE_BACKUP_SSH_IP}
      - REMOTE_BACKUP_SSH_PORT=${REMOTE_BACKUP_SSH_PORT}
      - REMOTE_BACKUP_USER=${REMOTE_BACKUP_USER}
      - REMOTE_BACKUP_PASS=${REMOTE_BACKUP_PASS}
      - REMOTE_BACKUP_PATH=${REMOTE_BACKUP_PATH}
      - REMOTE_BACKUP_BINLOG_PATH=${REMOTE_BACKUP_BINLOG_PATH}
    restart: unless-stopped

volumes:
  data:
